### ISSUE TITLE
How to use the initial DAG in the RESIT sample code?

### ISSUE THREAD

**Issue by FTamas77** [cdt15/lingam#135]
For example, we have this code here: https://github.com/cdt15/lingam/blob/master/docs/tutorial/resit.rst

In that, we create an array:

m = np.array([
    [0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 0, 1, 0]])

But we never use it. I am confused because the adjacency matrix contains only 1 after the fitting. Could you help me to clarify the input/output of that code?

**Comment by ikeuchi-screen** [comment]
Hi @FTamas77 ,

The `m` is an array that we are creating to draw the true DAG, so we do not use it to run RESIT.

Like the inputs and outputs of other algorithms, the dataset is the input and the adjacency matrix is the output. However, because of RESIT's assumption of nonlinear functions, the adjacency matrix will have a value of 0 or 1.

**Comment by FTamas77** [comment]
@ikeuchi-screen Thank you very much for the clarification. So, am I correct if I say that 1 means a correlation and zero means no correlation between the variables?

**Comment by ikeuchi-screen** [comment]
@FTamas77 
One in the adjacency matrix represents an edge in the causal graph, while zero represents no edge. Edges denote causation rather than correlation.

Because the relationship between variables is nonlinear, even `model.bootstrap` cannot estimate causal effects. Bootstrapping can estimate the probability of edges.

**Comment by FTamas77** [comment]
Thank you very much for the clarification.
